#!/usr/bin/env python3
"""Fail-closed repository evidence discovery for DO-DEP-01..14.

This tool inventories *references* to authoritative department IDs in tracked
repository text files. A reference is never treated as proof of deployment or
operational status. The generated report is deterministic and safe for CI.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "config/abe/department-manifest.json"
REPORT = ROOT / "docs/ABE/DEPARTMENT_EVIDENCE.md"
ID_RE = re.compile(r"DO-DEP-(?:0[1-9]|1[0-4])")
EXCLUDED = {
    "config/abe/department-manifest.json",
    "docs/ABE/DEPARTMENT_EVIDENCE.md",
    "scripts/abe/discover-department-evidence.py",
}


def tracked_files() -> list[str]:
    out = subprocess.check_output(["git", "ls-files", "-z"], cwd=ROOT)
    return sorted(x.decode() for x in out.split(b"\0") if x)


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    expected = [f"DO-DEP-{i:02d}" for i in range(1, 15)]
    actual = [d["id"] for d in manifest["departments"]]
    if actual != expected or manifest["scope"]["count"] != 14:
        raise SystemExit("Authoritative department scope invariant failed")

    refs = {dep: [] for dep in expected}
    for rel in tracked_files():
        if rel in EXCLUDED:
            continue
        path = ROOT / rel
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            for dep in sorted(set(ID_RE.findall(line))):
                refs[dep].append({"path": rel, "line": lineno})

    lines = [
        "# Department Evidence Discovery",
        "",
        "> Generated by `scripts/abe/discover-department-evidence.py`. Repository references are discovery leads only; they do **not** upgrade verification/deployment status.",
        "",
        "| Department | Manifest status | Repository reference leads |",
        "|---|---|---|",
    ]
    statuses = {d["id"]: d["evidence_status"] for d in manifest["departments"]}
    for dep in expected:
        leads = refs[dep]
        rendered = ", ".join(f"`{x['path']}:{x['line']}`" for x in leads[:8]) or "None"
        if len(leads) > 8:
            rendered += f" (+{len(leads)-8} more)"
        lines.append(f"| {dep} | {statuses[dep]} | {rendered} |")
    lines += [
        "",
        "## Reconciliation rule",
        "",
        "A department may be upgraded only from specific, reviewable evidence that proves the claimed state. Mere ID occurrence, planning text, generated inventory, or queue metadata is insufficient. External systems are not written by this discovery step.",
        "",
    ]
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(ROOT)}; authoritative scope: 14 departments")


if __name__ == "__main__":
    main()
